# Generated by Django 2.2 on 2021-07-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('instagram_link', models.CharField(max_length=255)),
                ('facebook_link', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='roles/')),
            ],
        ),
    ]
